In [5]:
import pandas as pd

# Ler o arquivo CSV
df = pd.read_csv("File.csv", header=None)

df

                                                        0
0       -1.200000000e+00;0.000000000e+00;-1.999938965e-08
1       -1.195200000e+00;0.000000000e+00;-1.999938965e-08
2       -1.190400000e+00;0.000000000e+00;-1.999938965e-08
3       -1.185600000e+00;0.000000000e+00;-1.999938965e-08
4       -1.180800000e+00;0.000000000e+00;-1.999938965e-08
...                                                   ...
204795    1.233600000e+00;4.000000000e+02;3.125610373e-09
204796    1.238400000e+00;4.000000000e+02;3.195800803e-09
204797    1.243200000e+00;4.000000000e+02;3.322753928e-09
204798    1.248000000e+00;4.000000000e+02;3.479003928e-09
204799    1.252800000e+00;4.000000000e+02;3.215332053e-09

[204800 rows x 1 columns]

In [20]:
import pandas as pd

# Ler o arquivo CSV usando ponto e vírgula como delimitador
df = pd.read_csv("File.csv", header=None, delimiter=';')

# Extrair apenas as colunas 1 e 3 (considerando a indexação iniciando em 0)
dados_iv = df.iloc[:, [0, 2]]

# Renomear as colunas para 'V' e 'I'
dados_iv.columns = ['V', 'I']

# Exibir as primeiras linhas do DataFrame resultante
dados_iv.head()

        V             I
0 -1.2000 -1.999939e-08
1 -1.1952 -1.999939e-08
2 -1.1904 -1.999939e-08
3 -1.1856 -1.999939e-08
4 -1.1808 -1.999939e-08

In [2]:
import pandas as pd

# Ler o arquivo CSV usando ponto e vírgula como delimitador
df = pd.read_csv("File.csv", header=None, delimiter=';')

# Extrair apenas as colunas 1 e 3 (considerando a indexação iniciando em 0)
dados_iv = df.iloc[:, [0, 2]]

# Renomear as colunas para 'V' e 'I'
dados_iv.columns = ['x', 'y']

# Dividir o DataFrame em 400 partes, cada uma contendo 512 linhas
curvas = [dados_iv[i:i+512]['y'].reset_index(drop=True) for i in range(0, len(dados_iv), 512)]

# Criar um único DataFrame para todas as curvas
df_final = pd.concat(curvas, axis=1)

# Renomear as colunas de corrente para 'y_1', 'y_2', ..., 'y_400'
df_final.columns = [f"y_{i}" for i in range(1, len(curvas) + 1)]

# Adicionar a coluna de voltagem ao DataFrame final
df_final['x'] = dados_iv['x'].iloc[:512].reset_index(drop=True)

# Reordenar as colunas para que 'x' seja a primeira coluna
df_final = df_final[['x'] + [f"y_{i}" for i in range(1, len(curvas) + 1)]]

# Salvar todas as curvas em um único arquivo CSV
df_final.to_csv("curvas_combined_F.csv", index=False)

df_final

,x,y_1,y_2,y_3,y_4,y_5,y_6,y_7,y_8,y_9,...,y_391,y_392,y_393,y_394,y_395,y_396,y_397,y_398,y_399,y_400
0,-1.2000,-4.658203e-09,-1.727295e-10,-1.954956e-09,-2.233887e-10,-1.126587e-08,-2.852783e-09,-3.670044e-09,-2.388306e-09,-9.485474e-09,...,-3.217163e-09,-4.605103e-09,-2.329712e-09,-3.771973e-09,-1.879883e-10,-7.910156e-10,-8.514404e-10,-3.106689e-10,-3.417969e-10,-3.278809e-09
1,-1.1952,-4.496460e-09,-1.647949e-10,-1.951904e-09,-2.130127e-10,-1.129944e-08,-2.941284e-09,-3.658447e-09,-2.435303e-09,-9.551392e-09,...,-2.979736e-09,-4.514160e-09,-2.489624e-09,-3.843994e-09,-1.812744e-10,-8.734131e-10,-8.551025e-10,-2.972412e-10,-3.393555e-10,-2.907104e-09
2,-1.1904,-4.209595e-09,-1.257324e-10,-1.773071e-09,-1.721191e-10,-1.136597e-08,-2.717895e-09,-3.622437e-09,-2.427368e-09,-9.278564e-09,...,-2.785645e-09,-4.376831e-09,-2.615356e-09,-3.618164e-09,-1.318359e-10,-7.965088e-10,-8.184814e-10,-2.514648e-10,-3.332519e-10,-2.630005e-09
3,-1.1856,-4.338379e-09,-9.765623e-11,-1.632080e-09,-1.580810e-10,-1.128479e-08,-2.650757e-09,-3.582153e-09,-2.380371e-09,-9.794922e-09,...,-2.756348e-09,-4.130859e-09,-2.514038e-09,-3.551025e-09,-1.068115e-10,-7.580566e-10,-8.032226e-10,-2.325439e-10,-3.430176e-10,-2.502441e-09
4,-1.1808,-4.307251e-09,-8.850096e-11,-1.488037e-09,-1.434326e-10,-1.152161e-08,-2.614746e-09,-3.571777e-09,-2.285767e-09,-1.026855e-08,...,-2.691650e-09,-4.572144e-09,-2.319946e-09,-3.452148e-09,-9.643553e-11,-7.586670e-10,-8.361816e-10,-2.221680e-10,-3.344726e-10,-2.447510e-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
507,1.2336,7.283325e-09,1.361084e-10,2.653809e-09,7.165528e-10,8.780518e-09,3.897095e-09,7.489624e-09,-2.000000e-08,5.142212e-09,...,5.370483e-09,5.072632e-09,7.943726e-09,8.352051e-09,1.357422e-09,5.562744e-09,1.292542e-08,1.509399e-09,8.008423e-09,4.844360e-09
508,1.2384,7.597046e-09,1.391602e-10,2.712402e-09,6.579590e-10,7.858276e-09,4.025269e-09,7.666626e-09,-2.000000e-08,5.051270e-09,...,5.036011e-09,5.358887e-09,8.588867e-09,8.165894e-09,1.431885e-09,5.861816e-09,8.908691e-09,1.547852e-09,7.777710e-09,4.729614e-09
509,1.2432,8.169556e-09,1.367188e-10,2.755737e-09,7.397461e-10,7.958374e-09,5.208740e-09,8.117676e-09,-2.000000e-08,4.791870e-09,...,4.929810e-09,5.274048e-09,8.843384e-09,8.894653e-09,1.391602e-09,5.542603e-09,7.755127e-09,1.711426e-09,7.785034e-09,4.542847e-09
510,1.2480,8.661499e-09,1.385498e-10,3.007202e-09,8.758545e-10,6.839600e-09,6.711426e-09,9.296265e-09,-2.000000e-08,4.868164e-09,...,6.945801e-09,5.318604e-09,9.475708e-09,9.810181e-09,1.306152e-09,5.256348e-09,8.189087e-09,1.696167e-09,7.678223e-09,5.061035e-09
511,1.2528,8.942871e-09,1.684570e-10,3.216553e-09,9.112549e-10,6.849365e-09,6.682129e-09,9.240112e-09,-2.000000e-08,4.769287e-09,...,7.806397e-09,5.684814e-09,9.705200e-09,1.057434e-08,1.252441e-09,6.149292e-09,7.487183e-09,1.687622e-09,7.852783e-09,5.497437e-09